# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 887a9edad2cc7ea7e6d5dc2e4f07f797f1e759b5f1c19314f3f19f75d7e6b74f127f2c5205e5cd5fe9ca485810c750182694f1f8b895b97f6aab896e95d0839e

test:
  secret_key_base: 64bf90ff922780dd88774b74de79494bc20ff9a53c0cabf46ee839799c083ae3f1edeeab40ac60b031ee2232ce2956fc9c3aeb55aead0db89de04277fcfd3c39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
